language: groovy
jdk:
  - oraclejdk8
addons:
  postgresql: "9.3"
services:
    - postgresql
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - extlib/
    - $HOME/.grails/
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/bower/
before_install:
    - npm install -g bower
before_script:
    - psql -c 'create database "apollo-test";' -U postgres;
    - git clone https://github.com/elsiklab/apollo_domain_classes.git
    - cd apollo_domain_classes && ./grailsw refresh-dependencies && ./grailsw maven-install && cd -
script:
    - ./grailsw test-app --non-interactive
